// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import ()

type Article struct {
	ArticleID int32
	Title     string
	Content   string
	Date      string
}

type User struct {
	UserID   int32
	Name     string
	Password string
}
